# Don't print a new line at the start of the prompt
add_newline = false

# Replace the "â¯" symbol in the prompt with "âœ"
[character]      # The name of the module we are configuring is "character"
success_symbol = "âœ"     # The "symbol" segment is being set to "âœ"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[gcloud]
# format = "[$symbol$account(\\($region\\))]($style) "
format = "[$symbol$active]($style) "

[git_branch]
format = "[$symbol$branch]($style) "
symbol = "ğŸŒ±"

[golang]
format = "[$symbol$version]($style) "
symbol = "ğŸ¹"

[helm]
format = "[$symbol$version]($style) "
symbol = "âˆ"
